name: Dependencies

on:
  push:
    branches: [ master ]
    tags:        
      - v1  
     
jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    env:  
      azmonRG: azmon-rg
      customerCode: pvdv
      locationShortName: weu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set Environment Variables
        run: echo ResouceGroup $azmonRG customerCode $customerCode locationShortName $locationShortName!


      - name: Login Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Log Analytics Workspace
        run: |
            az deployment group validate --name 'logAnalyticsWorkspaceDeployment' --resource-group $azmonRG --template-file Dependencies/LogAnalyticsWorkspace.json --parameters customerCode=$customerCode locationShortName=$locationShortName 

      - name: Upload Dependency Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Dependencies
          path: Dependencies/
