name: Dependencies

on:
  push:
    branches: [ master ]
    tags:        
      - v1  
     
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Upload Dependency Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Dependencies
          path: Dependencies/
