name: Dependencies

on:
  push:
    branches: [ master ]
    tags:        
      - v1  
     
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
