name: Dependencies

on:
  push:
    branches: [ master ]
    tags:        
      - v1  
     
jobs:
  build:
    # Job name is Greeting
    name: Dependencies
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
   
      - name: Login Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Log Analytics Workspace
        run: |
            az deployment group create --name 'logAnalyticsWorkspaceDeployment' --resource-group 'azmon-rg' --template-file Dependencies/LogAnalyticsWorkspace.json --parameters customerCode="pvdv" locationShortName="weu" 

      - name: Upload Dependency Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Dependencies
          path: Dependencies/
